# Generated by Django 2.2.12 on 2023-02-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'User'},
        ),
    ]
