# Generated by Django 4.2.1 on 2023-05-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_sales_id_alter_users_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('branchID', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
