# Generated by Django 4.2.1 on 2023-05-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_producers_producer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='branchID',
            new_name='producer_id',
        ),
    ]
