# Generated by Django 4.2.1 on 2023-05-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_producer_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='products',
        ),
    ]
