# Generated by Django 4.2.1 on 2023-05-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_producer_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producer',
        ),
    ]
