# Generated by Django 4.2.1 on 2023-05-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_producer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='producer_id',
            new_name='_id',
        ),
    ]
