# Generated by Django 4.2.1 on 2023-05-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_producer_id_producer__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='draft',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
