# Generated by Django 4.2.1 on 2023-05-09 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_producer_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='draft',
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.users'),
        ),
    ]
