# Generated by Django 2.2.12 on 2023-04-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230407_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branchID',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
